version: '3.5'

services:
  php-apache:
    build: .
    image: alexandregv/paheko:1.3.4
    restart: unless-stopped
    volumes:
      - data:/var/www/paheko/data/:rw
      - ./config.local.php:/var/www/paheko/config.local.php:rw
    environment:
      TZ: Europe/Paris
    ports:
      - '8080:80'

volumes:
  data:
